name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on:
      - self-hosted
      - greybotorg

    steps:
      - uses: actions/checkout@v2

      - name: Run on self-hosted server
        run: |
          cd ~/bot/greyBotOrg
          git pull
          echo "${{secrets.SERVER_PASSWORD}}"
          echo "${{secrets.SERVER_PASSWORD}}" | sudo -S -v
          sudo supervisorctl update
          sudo supervisorctl stop tgbot
          sudo supervisorctl start tgbot